/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoferreteria_7a.GUI;

import proyectoferreteria_7a.BO.FacturasBO;
import proyectoferreteria_7a.BO.PedidosBO;
import proyectoferreteria_7a.DAO.PedidosDAO;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daryl
 */
public class JFramePedidos extends javax.swing.JFrame 
{
    
    DefaultTableModel dtm = new DefaultTableModel(
    new Object [][] {
        /*{null, null, null, null}*/
    },
    new String [] {
        "ID_Pedido", "Fecha De Solicitud", "Número De Productos", "Cantidad"
    });
    String RutaArchivo;
    ImageIcon ImagenP;
    File Archivo ;
    private JFileChooser SelectorImagenes;
    PedidosBO ObjPedidosBO = new PedidosBO();
    PedidosDAO ObjPedidosDAO = new PedidosDAO();

    /**
     * Creates new form JFramePedidos
     */
    public JFramePedidos() {
        initComponents();
        this.setTitle("Gestión De Pedidos");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlblPedido = new javax.swing.JLabel();
        JlblFechaSolicitud = new javax.swing.JLabel();
        JlblNumeroProductos = new javax.swing.JLabel();
        JlblCantidad = new javax.swing.JLabel();
        JtxtPedido = new javax.swing.JTextField();
        JtxtFechaSolicitud = new javax.swing.JTextField();
        JtxtNumProductos = new javax.swing.JTextField();
        JtxtCantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTablePedidos = new javax.swing.JTable();
        JbtnAgregar = new javax.swing.JButton();
        JbtnEliminar = new javax.swing.JButton();
        JbtnModificar = new javax.swing.JButton();
        JbtnBuscar = new javax.swing.JButton();
        JbtnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JlblPedido.setText("ID Pedido :");

        JlblFechaSolicitud.setText("Fecha De Solicitud :");

        JlblNumeroProductos.setText("Número De Productos :");

        JlblCantidad.setText("Cantidad : ");

        JTablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTablePedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JTablePedidosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(JTablePedidos);

        JbtnAgregar.setText("Agregar");
        JbtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnAgregarActionPerformed(evt);
            }
        });

        JbtnEliminar.setText("Eliminar");
        JbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnEliminarActionPerformed(evt);
            }
        });

        JbtnModificar.setText("Modificar");
        JbtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnModificarActionPerformed(evt);
            }
        });

        JbtnBuscar.setText("Buscar");
        JbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuscarActionPerformed(evt);
            }
        });

        JbtnLimpiar.setText("Limpiar");
        JbtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JbtnAgregar)
                        .addGap(31, 31, 31)
                        .addComponent(JbtnEliminar)
                        .addGap(36, 36, 36)
                        .addComponent(JbtnModificar)
                        .addGap(27, 27, 27)
                        .addComponent(JbtnBuscar)
                        .addGap(26, 26, 26)
                        .addComponent(JbtnLimpiar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JlblPedido)
                            .addComponent(JlblFechaSolicitud)
                            .addComponent(JlblNumeroProductos)
                            .addComponent(JlblCantidad))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JtxtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(JtxtNumProductos)
                            .addComponent(JtxtFechaSolicitud)
                            .addComponent(JtxtPedido))))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlblPedido)
                    .addComponent(JtxtPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlblFechaSolicitud)
                    .addComponent(JtxtFechaSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlblNumeroProductos)
                    .addComponent(JtxtNumProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlblCantidad)
                    .addComponent(JtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbtnAgregar)
                    .addComponent(JbtnEliminar)
                    .addComponent(JbtnModificar)
                    .addComponent(JbtnBuscar)
                    .addComponent(JbtnLimpiar))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnAgregarActionPerformed
        // TODO add your handling code here:
        if(ObjPedidosDAO.Agregar(RecolectarDatos())==1)
        {
            JOptionPane.showMessageDialog(null,"Producto Agregado");
        }
     
     ActualizarTabla();
    }//GEN-LAST:event_JbtnAgregarActionPerformed

    private void JbtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnModificarActionPerformed
        // TODO add your handling code here:
        if(ObjPedidosDAO.Modificar(RecolectarDatos())==1)
        {
            JOptionPane.showMessageDialog(null,"Producto modificado");
        }        
        ActualizarTabla();
    }//GEN-LAST:event_JbtnModificarActionPerformed

    private void JbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnEliminarActionPerformed
        // TODO add your handling code here:
        if(ObjPedidosDAO.Eliminar(RecolectarDatos())==1)
        {
            JOptionPane.showMessageDialog(null,"Producto eliminada");
            Limpiar();
            ActualizarTabla();
        }     
        ActualizarTabla();
    }//GEN-LAST:event_JbtnEliminarActionPerformed

    private void JbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuscarActionPerformed
        // TODO add your handling code here:
        ActualizarTabla();
    }//GEN-LAST:event_JbtnBuscarActionPerformed

    private void JbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnLimpiarActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_JbtnLimpiarActionPerformed

    private void JTablePedidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTablePedidosMousePressed
        // TODO add your handling code here:
        JbtnAgregar.setEnabled(true);
        JbtnEliminar.setEnabled(true);
        JbtnModificar.setEnabled(true);
        JbtnAgregar.setEnabled(false);
        JtxtPedido.setText(JTablePedidos.getValueAt(JTablePedidos.getSelectedRow(), 0).toString());
        JtxtFechaSolicitud.setText(JTablePedidos.getValueAt(JTablePedidos.getSelectedRow(), 1).toString());
        JtxtNumProductos.setText(JTablePedidos.getValueAt(JTablePedidos.getSelectedRow(), 2).toString());
        JtxtCantidad.setText(JTablePedidos.getValueAt(JTablePedidos.getSelectedRow(), 3).toString());
      //JtxtCategoria.setText(JTableProductos.getValueAt(JTableProductos.getSelectedRow(), 4).toString());
      //JtxtEstatus.setText(JTableProductos.getValueAt(JTableProductos.getSelectedRow(), 5).toString());
      //cbxCIudad.setSelectedItem(JTableProductos.getValueAt(JTableProductos.getSelectedRow(), 5).toString());
      //RutaArchivo = JTablePedidos.getValueAt(JTablePedidos.getSelectedRow(), 6).toString();
    }//GEN-LAST:event_JTablePedidosMousePressed

    
    public void Limpiar(){
        
        JtxtPedido.setText("");
        JtxtFechaSolicitud.setText("");
        JtxtNumProductos.setText("");
        JtxtCantidad.setText("");
      //JtxtEstatus.setText("");
      //JtxtPrecio.setText("");
      //JtxtProducto.setText("");
      //JlblImagen.setIcon(null);
      //RutaArchivo = "";
      //txtDireccion.setText("");
      //JlblImagen.setIcon(new ImageIcon (Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Recursos/CargarFoto.png"))));
  /*
        btnEliminar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnAgregar.setEnabled(true);
        btnBuscar.setEnabled(true);      */
  }
    
    public void ActualizarTabla(){
    JTablePedidos.setModel(ObjPedidosDAO.Buscar(RecolectarDatos()));
    }
    
    public PedidosBO RecolectarDatos()
    {
        ObjPedidosBO.setFechaSolicitud(JtxtFechaSolicitud.getText());
        ObjPedidosBO.setId_Pedido(JtxtPedido.getText());
        ObjPedidosBO.setNumeroProductos(JtxtNumProductos.getText());
        ObjPedidosBO.setCantidad(JtxtCantidad.getText());
        
        return ObjPedidosBO;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTablePedidos;
    private javax.swing.JButton JbtnAgregar;
    private javax.swing.JButton JbtnBuscar;
    private javax.swing.JButton JbtnEliminar;
    private javax.swing.JButton JbtnLimpiar;
    private javax.swing.JButton JbtnModificar;
    private javax.swing.JLabel JlblCantidad;
    private javax.swing.JLabel JlblFechaSolicitud;
    private javax.swing.JLabel JlblNumeroProductos;
    private javax.swing.JLabel JlblPedido;
    private javax.swing.JTextField JtxtCantidad;
    private javax.swing.JTextField JtxtFechaSolicitud;
    private javax.swing.JTextField JtxtNumProductos;
    private javax.swing.JTextField JtxtPedido;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
