/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoferreteria_7a.GUI;

import proyectoferreteria_7a.BO.FacturasBO;
import proyectoferreteria_7a.BO.ProductosBO;
import proyectoferreteria_7a.DAO.FacturasDAO;
import proyectoferreteria_7a.DAO.PedidosDAO;
import proyectoferreteria_7a.DAO.ProductosDAO;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daryl
 */
public class JFrameProductos extends javax.swing.JFrame 
{
    
    DefaultTableModel dtm = new DefaultTableModel(
    new Object [][] {
        /*{null, null, null, null}*/
    },
    new String [] {
        "ID_Folio", "ID_Producto", "Nombre", "Precio", "Categoria", "Estatus", "Fecha"
    });
    String RutaArchivo;
    ImageIcon ImagenP;
    File Archivo ;
    private JFileChooser SelectorImagenes;
    FacturasBO ObjFacturasBO = new FacturasBO();
    FacturasDAO objFacturasDAO= new FacturasDAO();
    
    ProductosBO ObjProductosBO = new ProductosBO();
    ProductosDAO ObjProductosDAO = new ProductosDAO();

    /**
     * Creates new form JFrameProductos
     */
    public JFrameProductos() 
    {
        initComponents();
        this.setTitle("Gestión De Productos");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlblFolio = new javax.swing.JLabel();
        JtxtFolio = new javax.swing.JTextField();
        JlblFecha = new javax.swing.JLabel();
        JtxtFecha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        JtxtProducto = new javax.swing.JTextField();
        JlblNombre = new javax.swing.JLabel();
        JtxtNombreProducto = new javax.swing.JTextField();
        JlblPrecio = new javax.swing.JLabel();
        JtxtPrecio = new javax.swing.JTextField();
        JlblCategoria = new javax.swing.JLabel();
        JtxtCategoria = new javax.swing.JTextField();
        JlblEstatus = new javax.swing.JLabel();
        JtxtEstatus = new javax.swing.JTextField();
        JbtnExaminar = new javax.swing.JButton();
        JlblImagen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableProductos = new javax.swing.JTable();
        JbtnAgregar = new javax.swing.JButton();
        JbtnModificar = new javax.swing.JButton();
        JbtnEliminar = new javax.swing.JButton();
        JbtnBuscar = new javax.swing.JButton();
        JbtnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JlblFolio.setText("Folio :");

        JlblFecha.setText("Fecha :");

        jLabel1.setText("ID Producto :");

        JlblNombre.setText("Nombre :");

        JlblPrecio.setText("Precio :");

        JlblCategoria.setText("Categoría :");

        JlblEstatus.setText("Estatus :");

        JbtnExaminar.setText("Examinar...");
        JbtnExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnExaminarActionPerformed(evt);
            }
        });

        JlblImagen.setText("Foto");

        JTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JTableProductosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(JTableProductos);

        JbtnAgregar.setText("Agregar");
        JbtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnAgregarActionPerformed(evt);
            }
        });

        JbtnModificar.setText("Modificar");
        JbtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnModificarActionPerformed(evt);
            }
        });

        JbtnEliminar.setText("Eliminar");
        JbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnEliminarActionPerformed(evt);
            }
        });

        JbtnBuscar.setText("Buscar");
        JbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuscarActionPerformed(evt);
            }
        });

        JbtnLimpiar.setText("Limpiar");
        JbtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JbtnAgregar)
                        .addGap(32, 32, 32)
                        .addComponent(JbtnModificar)
                        .addGap(35, 35, 35)
                        .addComponent(JbtnEliminar)
                        .addGap(41, 41, 41)
                        .addComponent(JbtnBuscar)
                        .addGap(33, 33, 33)
                        .addComponent(JbtnLimpiar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JlblFolio)
                                        .addGap(53, 53, 53)
                                        .addComponent(JtxtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(JlblNombre)
                                            .addComponent(JlblPrecio)
                                            .addComponent(JlblCategoria)
                                            .addComponent(JlblEstatus))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JtxtEstatus)
                                            .addComponent(JtxtCategoria)
                                            .addComponent(JtxtPrecio)
                                            .addComponent(JtxtNombreProducto)
                                            .addComponent(JtxtProducto))))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JlblFecha)
                                        .addGap(18, 18, 18)
                                        .addComponent(JtxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(JlblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(240, 240, 240)
                                        .addComponent(JbtnExaminar))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(298, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JlblFolio)
                                    .addComponent(JtxtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JlblFecha)
                                    .addComponent(JtxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(JtxtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JlblNombre)
                                    .addComponent(JtxtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JlblPrecio)
                                    .addComponent(JtxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JlblCategoria)
                                    .addComponent(JtxtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JlblEstatus)
                            .addComponent(JtxtEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JlblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JbtnExaminar)
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JbtnAgregar)
                    .addComponent(JbtnModificar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JbtnEliminar)
                        .addComponent(JbtnBuscar)
                        .addComponent(JbtnLimpiar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnAgregarActionPerformed
        // TODO add your handling code here:
        if(objFacturasDAO.Agregar(RecolectarDatos())==1)
        {
            JOptionPane.showMessageDialog(null,"Producto Agregado");
        }
                        
        if(ObjProductosDAO.Agregar(RecolectarDatosP())==1)
        {
            JOptionPane.showMessageDialog(null,"Producto Agregado");
        }
     
     ActualizarTabla();
    }//GEN-LAST:event_JbtnAgregarActionPerformed

    private void JbtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnModificarActionPerformed
        // TODO add your handling code here:
        if(objFacturasDAO.Modificar(RecolectarDatos())==1)
        {
            JOptionPane.showMessageDialog(null,"Producto modificado");
        }        
        ActualizarTabla();
    }//GEN-LAST:event_JbtnModificarActionPerformed

    private void JbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnEliminarActionPerformed
        // TODO add your handling code here:
        if(objFacturasDAO.Eliminar(RecolectarDatos())==1)
        {
            JOptionPane.showMessageDialog(null,"Producto eliminada");
            Limpiar();
            ActualizarTabla();
        }     
        ActualizarTabla();
    }//GEN-LAST:event_JbtnEliminarActionPerformed

    private void JbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuscarActionPerformed
        // TODO add your handling code here:
        ActualizarTabla();
    }//GEN-LAST:event_JbtnBuscarActionPerformed

    private void JbtnExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnExaminarActionPerformed
        // TODO add your handling code here:
        
        SelectorImagenes = new JFileChooser();
        if(SelectorImagenes.showOpenDialog(null)== JFileChooser.APPROVE_OPTION)
        {
            RutaArchivo = "";
            Archivo = SelectorImagenes.getSelectedFile();
            RutaArchivo = Archivo.getAbsolutePath();
           //ImageIcon ImagenP= new ImageIcon(((new ImageIcon(RutaArchivo)).getImage()).getScaledInstance(300,300, java.awt.Image.SCALE_SMOOTH));
            ImagenP= new ImageIcon(((new ImageIcon(RutaArchivo)).getImage()).getScaledInstance(JlblImagen.getWidth(),JlblImagen.getHeight(), java.awt.Image.SCALE_SMOOTH));
            JlblImagen.setIcon(ImagenP);
            
        }
        else
        {
            RutaArchivo = "";
            JlblImagen.setIcon(null);
        }
    }//GEN-LAST:event_JbtnExaminarActionPerformed

    private void JbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnLimpiarActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_JbtnLimpiarActionPerformed

    private void JTableProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableProductosMousePressed
        // TODO add your handling code here:
        //txtDireccion.setText("");
        JbtnAgregar.setEnabled(true);
        JbtnEliminar.setEnabled(true);
        JbtnModificar.setEnabled(true);
        JbtnAgregar.setEnabled(false);
        JtxtFolio.setText(JTableProductos.getValueAt(JTableProductos.getSelectedRow(), 0).toString());
        JtxtProducto.setText(JTableProductos.getValueAt(JTableProductos.getSelectedRow(), 1).toString());
        JtxtNombreProducto.setText(JTableProductos.getValueAt(JTableProductos.getSelectedRow(), 2).toString());
        JtxtPrecio.setText(JTableProductos.getValueAt(JTableProductos.getSelectedRow(), 3).toString());
        JtxtCategoria.setText(JTableProductos.getValueAt(JTableProductos.getSelectedRow(), 4).toString());
        JtxtEstatus.setText(JTableProductos.getValueAt(JTableProductos.getSelectedRow(), 5).toString());
      //cbxCIudad.setSelectedItem(JTableProductos.getValueAt(JTableProductos.getSelectedRow(), 5).toString());
        RutaArchivo = JTableProductos.getValueAt(JTableProductos.getSelectedRow(), 6).toString();
      //txtDireccion.setText(JTableProductos.getValueAt(JTableProductos.getSelectedRow(), 7).toString());
        
        /*RutaArchivo=(tblUsuarios.getValueAt(tblUsuarios.getSelectedRow(), 6).toString());*/
            if (JTableProductos.getValueAt(JTableProductos.getSelectedRow(), 6).toString().equals(""))
            {            
                JlblImagen.setIcon(new ImageIcon (Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("recursos/CargarFoto.png"))));
            }
            else
            {
                JlblImagen.setIcon(null);
                ImagenP= new ImageIcon(((new ImageIcon((JTableProductos.getValueAt(JTableProductos.getSelectedRow(), 6).toString()))).getImage()).getScaledInstance(JlblImagen.getWidth(),JlblImagen.getHeight(), java.awt.Image.SCALE_SMOOTH));
                JlblImagen.setIcon(ImagenP);
            }      
    }//GEN-LAST:event_JTableProductosMousePressed

    public FacturasBO RecolectarDatos()
    {
        ObjFacturasBO.setId_Folio(JtxtFolio.getText());
        ObjFacturasBO.setFecha(JtxtFecha.getText());       
        //ObjFacturasBO.setApellidos(txtApellidos.getText());
        //ObjFacturasBO.setCorreo(txtCorreo.getText());
        //ObjFacturasBO.setEstado(cbxEstado.getSelectedItem().toString());
        //ObjFacturasBO.setCiudad(cbxCIudad.getSelectedItem().toString());
        //ObjFacturasBO.setImagen(RutaArchivo);
        //ObjFacturasBO.setDireccion(txtDireccion.getText());  
        return ObjFacturasBO;
    }
    
    public ProductosBO RecolectarDatosP()
    {
        ObjProductosBO.setId_Producto(JtxtProducto.getText());
        ObjProductosBO.setCantidad(JtxtNombreProducto.getText());
        ObjProductosBO.setPrecio(JtxtPrecio.getText());
        ObjProductosBO.setEstatus(JtxtEstatus.getText());
        ObjProductosBO.setCategoria(JtxtCategoria.getText());
        
        return ObjProductosBO;
    }

    
    public void ActualizarTabla(){
    JTableProductos.setModel(objFacturasDAO.Buscar(RecolectarDatos()));
    }
    
    public void Limpiar(){
        
        JtxtFolio.setText("");
        JtxtNombreProducto.setText("");
        JtxtFecha.setText("");
        JtxtCategoria.setText("");
        JtxtEstatus.setText("");
        JtxtPrecio.setText("");
        JtxtProducto.setText("");
        JlblImagen.setIcon(null);
        RutaArchivo = "";
      //txtDireccion.setText("");
      //JlblImagen.setIcon(new ImageIcon (Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Recursos/CargarFoto.png"))));
  /*
        btnEliminar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnAgregar.setEnabled(true);
        btnBuscar.setEnabled(true);      */
  }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableProductos;
    private javax.swing.JButton JbtnAgregar;
    private javax.swing.JButton JbtnBuscar;
    private javax.swing.JButton JbtnEliminar;
    private javax.swing.JButton JbtnExaminar;
    private javax.swing.JButton JbtnLimpiar;
    private javax.swing.JButton JbtnModificar;
    private javax.swing.JLabel JlblCategoria;
    private javax.swing.JLabel JlblEstatus;
    private javax.swing.JLabel JlblFecha;
    private javax.swing.JLabel JlblFolio;
    private javax.swing.JLabel JlblImagen;
    private javax.swing.JLabel JlblNombre;
    private javax.swing.JLabel JlblPrecio;
    private javax.swing.JTextField JtxtCategoria;
    private javax.swing.JTextField JtxtEstatus;
    private javax.swing.JTextField JtxtFecha;
    private javax.swing.JTextField JtxtFolio;
    private javax.swing.JTextField JtxtNombreProducto;
    private javax.swing.JTextField JtxtPrecio;
    private javax.swing.JTextField JtxtProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
