/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoferreteria_7a.GUI;

import proyectoferreteria_7a.BO.FacturasBO;
import proyectoferreteria_7a.BO.ProductosBO;
import proyectoferreteria_7a.DAO.FacturasDAO;
import proyectoferreteria_7a.DAO.ProductosDAO;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import proyectoferreteria_7a.GUI.JFramePedidos;
import javax.swing.WindowConstants;

/**
 *
 * @author Daryl
 */
public class Productos extends javax.swing.JFrame 
{
    
    DefaultTableModel dtm = new DefaultTableModel(
    new Object [][] 
    {
        //{null, null, null, null }
    },
    new String [] {
        "ID_Producto", "Cantidad", "Precio", "Estatus", "Categoría", "Imagen", "Productos"
    }
);
    
    String RutaArchivo;
    ImageIcon Imagen;
    File Archivo;
    private JFileChooser SeleccionarImagen;
    
    private TableRowSorter trsFiltro;
    
    
    FacturasBO ObjFacturasBO = new FacturasBO();
    FacturasDAO ObjFacturasDAO = new FacturasDAO();
    
    
    
    ProductosBO ObjProductosBO = new ProductosBO();
    ProductosDAO objProductosDAO= new ProductosDAO();

    
    /**
     * Creates new form Productos
     */
    public Productos() 
    {
        initComponents();
        this.setTitle("Gestión De Productos");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JtxtProducto = new javax.swing.JTextField();
        JtxtCantidad = new javax.swing.JTextField();
        jbtnAgregar = new javax.swing.JButton();
        jbtnModificar = new javax.swing.JButton();
        JbtnLimpiar = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        txtFiltro = new javax.swing.JTextField();
        jbtnBuscar = new javax.swing.JButton();
        JlblProducto = new javax.swing.JLabel();
        jlblImagen = new javax.swing.JLabel();
        jbtnExaminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        JlblCantidad = new javax.swing.JLabel();
        JtxtEstatus = new javax.swing.JTextField();
        JlblPrecio = new javax.swing.JLabel();
        JtxtPrecio = new javax.swing.JTextField();
        JlblEstatus = new javax.swing.JLabel();
        JlblImagen = new javax.swing.JLabel();
        JcmxOpcion = new javax.swing.JComboBox<>();
        JcmxCategoria = new javax.swing.JComboBox<>();
        JcmxProductos = new javax.swing.JComboBox<>();
        jlblEstado = new javax.swing.JLabel();
        jlblCiudad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JtxtProducto.setEnabled(false);

        jbtnAgregar.setText("Agregar");
        jbtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarActionPerformed(evt);
            }
        });

        jbtnModificar.setText("Modificar");
        jbtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModificarActionPerformed(evt);
            }
        });

        JbtnLimpiar.setText("Limpiar");
        JbtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnLimpiarActionPerformed(evt);
            }
        });

        jbtnEliminar.setText("Eliminar");
        jbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarActionPerformed(evt);
            }
        });

        txtFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltroActionPerformed(evt);
            }
        });
        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFiltroKeyTyped(evt);
            }
        });

        jbtnBuscar.setText("Buscar");
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });

        JlblProducto.setText("ID Producto :");

        jbtnExaminar.setText("Examinar...");
        jbtnExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExaminarActionPerformed(evt);
            }
        });

        jTableProductos.setModel(dtm);
        jTableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableProductosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProductos);

        JlblCantidad.setText("Cantidad :");

        JlblPrecio.setText("Precio :");

        JlblEstatus.setText("Estatus :");

        JlblImagen.setText("Foto");

        JcmxOpcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pedidos" }));
        JcmxOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcmxOpcionActionPerformed(evt);
            }
        });

        JcmxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una Categoría", "Herramientas De Mano", "Tuberías", "Pinturas" }));
        JcmxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcmxCategoriaActionPerformed(evt);
            }
        });

        JcmxProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "\" \"" }));
        JcmxProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JcmxProductosMousePressed(evt);
            }
        });

        jlblEstado.setText("Categoría");

        jlblCiudad.setText("Productos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jbtnAgregar)
                                            .addGap(18, 18, 18)
                                            .addComponent(jbtnModificar)
                                            .addGap(18, 18, 18)
                                            .addComponent(jbtnEliminar))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(JlblCantidad)
                                            .addGap(38, 38, 38)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(JtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(JtxtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(JtxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(JtxtEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(JlblProducto)
                                        .addComponent(JlblPrecio)
                                        .addComponent(JlblEstatus))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlblEstado)
                                        .addGap(208, 208, 208)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jbtnBuscar)
                                        .addGap(18, 18, 18)
                                        .addComponent(JbtnLimpiar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JlblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(jbtnExaminar)))
                                        .addGap(335, 335, 335)
                                        .addComponent(jlblImagen))))
                            .addComponent(jlblCiudad)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(JcmxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JcmxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(33, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JcmxOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(JcmxOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JlblProducto)
                                    .addComponent(JtxtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JlblCantidad)
                                    .addComponent(JtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JlblPrecio)
                                    .addComponent(JtxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JlblEstatus)
                                    .addComponent(JtxtEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(JlblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtnExaminar)
                                    .addComponent(jlblEstado))))
                        .addGap(18, 18, 18)
                        .addComponent(JcmxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlblCiudad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JcmxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 59, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnAgregar)
                    .addComponent(jbtnModificar)
                    .addComponent(jbtnEliminar)
                    .addComponent(jbtnBuscar)
                    .addComponent(JbtnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarActionPerformed
        // TODO add your handling code here:

        /*Instrucción del botón Agregar para la base de datos
        UsuariosDAO ObjUsuariosDAO = new UsuariosDAO();
        ObjUsuariosDAO.Agregar(RecolectarDatos());

        Object[] fila = { ObjUsuariosBO.getCodigo(), ObjUsuariosBO.getNombres(), ObjUsuariosBO.getApellidos(), ObjUsuariosBO.getCorreo(), ObjUsuariosBO.getEstado(), ObjUsuariosBO.getCiudad()};//JcmxEstado.getSelectedItem(), JcmxCiudad.getSelectedItem() };
        dtm.addRow(fila);
        */
        /*
        if(JcmxOpcion.getSelectedItem().equals("Pedidos"))
        {
           String sql = "INSERT INTO Pedidos VALUES (?,?,?)";
        }
        */
        
        
        
        
        if(objProductosDAO.Agregar(RecolectarDatosP())==1)
        {
            JOptionPane.showMessageDialog(null,"Información Agregada");
        }

        ActualizarTabla();

    }//GEN-LAST:event_jbtnAgregarActionPerformed

    private void jbtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModificarActionPerformed
        // TODO add your handling code here:
        if(objProductosDAO.Modificar(RecolectarDatosP())==1)
        {
            JOptionPane.showMessageDialog(null,"Información modificada");
        }
        ActualizarTabla();
    }//GEN-LAST:event_jbtnModificarActionPerformed

    private void JbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnLimpiarActionPerformed
        // TODO add your handling code here:
        Limpiar();
        jbtnEliminar.setEnabled(false);
        jbtnModificar.setEnabled(false);
        jbtnAgregar.setEnabled(true);
        jbtnBuscar.setEnabled(true);
        //JcmxCiudad.removeAllItems();
        //JcmxCiudad.addItem(" ");
        JcmxCategoria.setSelectedItem("Seleccione una opción");
    }//GEN-LAST:event_JbtnLimpiarActionPerformed

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
        // TODO add your handling code here:
        if(objProductosDAO.Eliminar(RecolectarDatosP())==1)
        {
            JOptionPane.showMessageDialog(null,"Información eliminada");
        }
        ActualizarTabla();
    }//GEN-LAST:event_jbtnEliminarActionPerformed

    private void txtFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltroActionPerformed

    private void txtFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyTyped
        // TODO add your handling code here:
        txtFiltro.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (txtFiltro.getText());
                txtFiltro.setText(cadena);
                repaint();
                Filtro();
            }
        });
        trsFiltro = new TableRowSorter(jTableProductos.getModel());
        jTableProductos.setRowSorter(trsFiltro);
    }//GEN-LAST:event_txtFiltroKeyTyped

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        // TODO add your handling code here:

        ActualizarTabla();
    }//GEN-LAST:event_jbtnBuscarActionPerformed

    private void jbtnExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExaminarActionPerformed
        // TODO add your handling code here:
        SeleccionarImagen = new JFileChooser();

        if (SeleccionarImagen.showOpenDialog(null) == JFileChooser.APPROVE_OPTION)
        {
            RutaArchivo = "";
            Archivo = SeleccionarImagen.getSelectedFile();
            RutaArchivo = Archivo.getAbsolutePath();
            Imagen = new ImageIcon(((new ImageIcon(RutaArchivo)).getImage()).getScaledInstance(JlblImagen.getWidth(), JlblImagen.getHeight(), java.awt.Image.SCALE_SMOOTH));
            JlblImagen.setIcon(Imagen);
        }
        else
        {
            RutaArchivo = "";
            JlblImagen.setIcon(null);
        }
    }//GEN-LAST:event_jbtnExaminarActionPerformed

    private void jTableProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductosMouseClicked
        // TODO add your handling code here:

        int row = jTableProductos.getSelectedRow();
        System.out.println("--"+row);
        JTable target = (JTable)evt.getSource();
        //JtxtFolio.setText(target.getValueAt(target.getSelectedRow(), 0).toString());
        JtxtProducto.setText(target.getValueAt(target.getSelectedRow(), 0).toString());
        //JtxtFecha.setText(target.getValueAt(target.getSelectedRow(), 2).toString());
        JtxtCantidad.setText(target.getValueAt(target.getSelectedRow(), 1).toString());
        JtxtPrecio.setText(target.getValueAt(target.getSelectedRow(), 2).toString());
        JcmxCategoria.setSelectedItem(target.getValueAt(target.getSelectedRow(), 3).toString());
        JcmxProductos.setSelectedItem(target.getValueAt(target.getSelectedRow(), 4).toString());
        JtxtEstatus.setText(target.getValueAt(target.getSelectedRow(), 5).toString());
        RutaArchivo = jTableProductos.getValueAt(jTableProductos.getSelectedRow(), 6).toString();

        if (jTableProductos.getValueAt(jTableProductos.getSelectedRow(), 6).toString().equals(""))
        {
            JlblImagen.setIcon(null);
        }
        else
        {
            Imagen= new ImageIcon(((new ImageIcon((jTableProductos.getValueAt(jTableProductos.getSelectedRow(), 6).toString()))).getImage()).getScaledInstance(JlblImagen.getWidth(),JlblImagen.getHeight(), java.awt.Image.SCALE_SMOOTH));
            JlblImagen.setIcon(Imagen);
        }

        jbtnEliminar.setEnabled(true);
        jbtnModificar.setEnabled(true);
        jbtnAgregar.setEnabled(false);
        jbtnBuscar.setEnabled(true);

    }//GEN-LAST:event_jTableProductosMouseClicked

    private void jTableProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductosMousePressed
        // TODO add your handling code here:
        /*
        jbtnAgregar.setEnabled(true);
        jbtnEliminar.setEnabled(true);
        jbtnModificar.setEnabled(true);
        jbtnAgregar.setEnabled(false);
        jtxtCodigo.setText(jTableUsuarios.getValueAt(jTableUsuarios.getSelectedRow(), 0).toString());
        jtxtNombre.setText(jTableUsuarios.getValueAt(jTableUsuarios.getSelectedRow(), 1).toString());
        jtxtApellidos.setText(jTableUsuarios.getValueAt(jTableUsuarios.getSelectedRow(), 2).toString());
        jtxtCorreo.setText(jTableUsuarios.getValueAt(jTableUsuarios.getSelectedRow(), 3).toString());
        JcmxEstado.setSelectedItem(jTableUsuarios.getValueAt(jTableUsuarios.getSelectedRow(), 4).toString());
        JcmxCiudad.setSelectedItem(jTableUsuarios.getValueAt(jTableUsuarios.getSelectedRow(), 5).toString());
        Ruta = jTableUsuarios.getValueAt(jTableUsuarios.getSelectedRow(), 6).toString();

        /*RutaArchivo=(tblUsuarios.getValueAt(tblUsuarios.getSelectedRow(), 6).toString());
        if (jTableUsuarios.getValueAt(jTableUsuarios.getSelectedRow(), 6).toString().equals(""))
        {
            jlblImagen.setIcon(null);
        }
        else
        {
            Imagen= new ImageIcon(((new ImageIcon((jTableUsuarios.getValueAt(jTableUsuarios.getSelectedRow(), 6).toString()))).getImage()).getScaledInstance(jlblImagen.getWidth(),jlblImagen.getHeight(), java.awt.Image.SCALE_SMOOTH));
            jlblImagen.setIcon(Imagen);
        }
        */
    }//GEN-LAST:event_jTableProductosMousePressed

    private void JcmxOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcmxOpcionActionPerformed
        // TODO add your handling code here:
        if(JcmxOpcion.getSelectedItem().equals("Pedidos"))
        {
            Pedidos ventana = new Pedidos();
            ventana.setDefaultCloseOperation(Pedidos.DISPOSE_ON_CLOSE);
            ventana.setVisible(true);
        }
        
        /*
        else
            
        if(JcmxOpcion.getSelectedItem().equals("Productos"))    
        {
            JFrameProductos ventana = new JFrameProductos();
            ventana.setVisible(true);
        }
        
        */
    }//GEN-LAST:event_JcmxOpcionActionPerformed

    private void JcmxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcmxCategoriaActionPerformed
        // TODO add your handling code here:
        LlenarCombobox();
    }//GEN-LAST:event_JcmxCategoriaActionPerformed

    private void JcmxProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JcmxProductosMousePressed
        // TODO add your handling code here:
        LlenarCombobox();
    }//GEN-LAST:event_JcmxProductosMousePressed

    
    public void ActualizarTabla()
    {
        jTableProductos.setModel(objProductosDAO.Buscar(RecolectarDatosP()));
    }
    
    public void Limpiar()
    {
        
      //JtxtFolio.setText("");
        JtxtCantidad.setText("");
      //JtxtFecha.setText("");
      //JcmxCategoria.getSelectedItem("");
        JtxtEstatus.setText("");
        JtxtPrecio.setText("");
        JtxtProducto.setText("");
        JlblImagen.setIcon(null);
        RutaArchivo = "";
      //txtDireccion.setText("");
      //JlblImagen.setIcon(new ImageIcon (Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Recursos/CargarFoto.png"))));
  /*
        btnEliminar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnAgregar.setEnabled(true);
        btnBuscar.setEnabled(true);      */
  }
    
    
    public FacturasBO RecolectarDatos()
    {
        //ObjFacturasBO.setId_Folio(JtxtFolio.getText());
        //ObjFacturasBO.setFecha(JtxtFecha.getText());       
        //ObjFacturasBO.setApellidos(txtApellidos.getText());
        //ObjFacturasBO.setCorreo(txtCorreo.getText());
        //ObjFacturasBO.setEstado(cbxEstado.getSelectedItem().toString());
        //ObjFacturasBO.setCiudad(cbxCIudad.getSelectedItem().toString());
        //ObjFacturasBO.setImagen(RutaArchivo);
        //ObjFacturasBO.setDireccion(txtDireccion.getText()); 
        
        return ObjFacturasBO;
    }
    
    public ProductosBO RecolectarDatosP()
    {
        ObjProductosBO.setId_Producto(JtxtProducto.getText());
        ObjProductosBO.setCantidad(JtxtCantidad.getText());
        ObjProductosBO.setPrecio(JtxtPrecio.getText());
        ObjProductosBO.setEstatus(JtxtEstatus.getText());     
        ObjProductosBO.setCategoria(JcmxCategoria.getSelectedItem().toString());
        ObjProductosBO.setProducto(JcmxProductos.getSelectedItem().toString());        
        ObjProductosBO.setImagen(RutaArchivo);
        
        return ObjProductosBO;
    }

    

    public void Filtro()
    {
        trsFiltro.setRowFilter(RowFilter.regexFilter(txtFiltro.getText(),0,1,2,3,4,5,6));
    }
    
    
    
    
    public void LlenarCombobox()
    {
            if (JcmxCategoria.getSelectedItem().equals("Herramientas De Mano"))
        {
            JcmxProductos.removeAllItems();
            JcmxProductos.addItem("Alicates");
            JcmxProductos.addItem("Cepillos Metálicos");
            JcmxProductos.addItem("Cutters");
            JcmxProductos.addItem("Destornilladores");
            JcmxProductos.addItem("Extractores");
            JcmxProductos.addItem("Limas y Escofinas");
            JcmxProductos.addItem("Llaves Ajustables");
            JcmxProductos.addItem("Llaves Alien");
            JcmxProductos.addItem("Llaves Fijas");
            JcmxProductos.addItem("Sierras De Mano");                       
        }
        if (JcmxCategoria.getSelectedItem().equals("Tuberías"))
        {
            JcmxProductos.removeAllItems();
            JcmxProductos.addItem("Bridas");
            JcmxProductos.addItem("Codos");
            JcmxProductos.addItem("Enchufes rápidos");
            JcmxProductos.addItem("Purgadores");
            JcmxProductos.addItem("Rácores");
            JcmxProductos.addItem("Mirillas");
            JcmxProductos.addItem("Mangueras Flexibles");
            JcmxProductos.addItem("Tubería De Aluminio");
            JcmxProductos.addItem("Tubéria De Acero");
            JcmxProductos.addItem("Tubería De Plástico");        

        }
        if (JcmxCategoria.getSelectedItem().equals("Pinturas"))
        {
            JcmxProductos.removeAllItems();
            JcmxProductos.addItem("Esmalte");
            JcmxProductos.addItem("Pintura Roja");
            JcmxProductos.addItem("Pintura Negra");
            JcmxProductos.addItem("Pintura Amarilla");
            JcmxProductos.addItem("Pintura Verde");
            JcmxProductos.addItem("Pintura Azul");
            JcmxProductos.addItem("Pintura Gris");
            JcmxProductos.addItem("Pintura Café");
            JcmxProductos.addItem("Pintura Morada");
            JcmxProductos.addItem("Pintura Rosada");                       
        }
        
        if (JcmxCategoria.getSelectedItem().equals("Seleccione una categoría"))
        {
            JcmxProductos.removeAllItems();
            JcmxProductos.addItem("");
        }
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnLimpiar;
    private javax.swing.JComboBox<String> JcmxCategoria;
    private javax.swing.JComboBox<String> JcmxOpcion;
    private javax.swing.JComboBox<String> JcmxProductos;
    private javax.swing.JLabel JlblCantidad;
    private javax.swing.JLabel JlblEstatus;
    private javax.swing.JLabel JlblImagen;
    private javax.swing.JLabel JlblPrecio;
    private javax.swing.JLabel JlblProducto;
    private javax.swing.JTextField JtxtCantidad;
    private javax.swing.JTextField JtxtEstatus;
    private javax.swing.JTextField JtxtPrecio;
    private javax.swing.JTextField JtxtProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JButton jbtnAgregar;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JButton jbtnExaminar;
    private javax.swing.JButton jbtnModificar;
    private javax.swing.JLabel jlblCiudad;
    private javax.swing.JLabel jlblEstado;
    private javax.swing.JLabel jlblImagen;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
