/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyectoferreteria_7a.GUI;

import javax.swing.table.DefaultTableModel;
import proyectoferreteria_7a.BO.UsuariosBO;
import proyectoferreteria_7a.Conexion.Conexion;
import proyectoferreteria_7a.DAO.UsuariosDAO;
import java.awt.Image;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * 
 */
public class Usuarios extends javax.swing.JFrame {
    
    private TableRowSorter trsFiltro;
     private JPanel contentPane;
     File fichero = null; 
    DefaultTableModel dtm= new DefaultTableModel(
    new Object [][] { },
    new String [] {
        "Código", "Nombres", "Apellidos", "FechaNacimiento", "Edad", "Direccion", "Telefono", "Correo", "Estado", "Ciudad", "Nacionlidad", "Puesto", "Imagen"
    });
    UsuariosBO ObjUsuariosBO= new UsuariosBO();
    UsuariosDAO objUsuariosDAO= new UsuariosDAO();
    
    String Ruta;
    ImageIcon Imagen;
    File Archivo;
    private JFileChooser SeleccionarImagen;
    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
        ActualizarTabla();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(Usuarios.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        cmbCiudad = new javax.swing.JComboBox<>();
        lblEstado = new javax.swing.JLabel();
        lblCiudad = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        txt_ruta = new javax.swing.JTextField();
        cmbBuscar = new javax.swing.JComboBox<>();
        lblBuscarPor = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar1 = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        btnExaminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        cmbNacionalidad = new javax.swing.JComboBox<>();
        lblCiudad1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPuesto = new javax.swing.JTextField();
        txtFiltro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código:");

        jLabel2.setText("Nombres:");

        jLabel3.setText("Apellidos:");

        jLabel4.setText("Fecha De Nacimiento:");

        txtCodigo.setEnabled(false);

        txtNombres.setText(" ");
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });

        txtFecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFechaFocusLost(evt);
            }
        });
        txtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaKeyTyped(evt);
            }
        });

        txtApellidos.setText(" ");
        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosKeyTyped(evt);
            }
        });

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/add.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/edit.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/delete.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/search.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblUsuarios.setModel(dtm);
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/clean.png"))); // NOI18N
        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmbCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "\" \"" }));

        lblEstado.setText("Estado:");

        lblCiudad.setText("Ciudad:");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Yucatán", "Quintana Roo", "México" }));
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });

        txt_ruta.setEnabled(false);

        cmbBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nombres", "Apellidos", "FechaNacimiento", "Edad", "Direccion", "Telefono", "Correo", "Estado", "Ciudad", "Nacionalidad", "Puesto", "Imagen", " " }));

        lblBuscarPor.setText("Buscar Por:");

        btnBuscar1.setText("Buscar");
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });

        lblImagen.setText("Imagen");

        btnExaminar.setText("Examinar...");
        btnExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExaminarActionPerformed(evt);
            }
        });

        jLabel5.setText("Edad:");

        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
        });

        jLabel6.setText("Dirección:");

        jLabel7.setText("Teléfono:");

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        jLabel8.setText("Correo:");

        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoFocusLost(evt);
            }
        });

        cmbNacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Mexicana", "Americana" }));

        lblCiudad1.setText("Nacionalidad:");

        jLabel9.setText("Puesto:");

        txtPuesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPuestoKeyTyped(evt);
            }
        });

        txtFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltroActionPerformed(evt);
            }
        });
        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFiltroKeyTyped(evt);
            }
        });

        jLabel10.setText("dd/MM/yyyy");

        jLabel11.setText("TuCorreo@gmail.com");

        jMenu7.setText("Menú");

        jMenuItem10.setText("Salir");
        jMenu7.add(jMenuItem10);

        jMenuBar4.add(jMenu7);

        jMenu8.setText("Ferreteria");

        jMenuItem11.setText("Clientes");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem11);

        jMenuItem3.setText("Ventas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem3);

        jMenuItem4.setText("Proveedores");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem4);

        jMenuItem5.setText("Empleados");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem5);

        jMenuItem8.setText("Consultas Facturas");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem8);

        jMenuItem9.setText("Consultas Ventas");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem9);

        jMenuBar4.add(jMenu8);

        setJMenuBar(jMenuBar4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(txt_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnExaminar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCiudad1)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCiudad)
                                    .addGap(18, 18, 18)
                                    .addComponent(cmbCiudad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblEstado)
                                    .addGap(22, 22, 22)
                                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)
                                        .addGap(2, 2, 2)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtDireccion))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(333, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBuscarPor)
                                .addGap(18, 18, 18)
                                .addComponent(cmbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 75, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExaminar)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCiudad1)
                                    .addComponent(cmbNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCiudad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnBuscar)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarPor)
                    .addComponent(cmbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar1)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       String nombres=txtNombres.getText();
       String apellidos=txtApellidos.getText();
       String fecha = txtFecha.getText();
       String edad=txtEdad.getText();
       String direccion=txtDireccion.getText();
       String telefono=txtTelefono.getText();
       String correo=txtCorreo.getText();
       String puesto=txtPuesto.getText();
       String estado = cmbEstado.getSelectedItem().toString();
       String ciudad = cmbCiudad.getSelectedItem().toString();
       String nacionalidad = cmbNacionalidad.getSelectedItem().toString();
       String imagen = lblImagen.getText();
       
       if(nombres.equalsIgnoreCase("")|| apellidos.equalsIgnoreCase("") || fecha.equalsIgnoreCase("") || edad.equalsIgnoreCase("") || direccion.equalsIgnoreCase("") || telefono.equalsIgnoreCase("") || correo.equalsIgnoreCase("") || estado.equalsIgnoreCase("Seleccione...") || ciudad.equalsIgnoreCase("\" \"") || nacionalidad.equalsIgnoreCase("Seleccione...") || puesto.equalsIgnoreCase("") || imagen.equalsIgnoreCase("Imagen")){
       JOptionPane.showMessageDialog(null,"Faltan Ingresar Datos");
            
        }        
        
       else if(objUsuariosDAO.Agregar(RecoletarDatos())==1)
        {
            JOptionPane.showMessageDialog(null,"Información Agregada");
        }
     
     ActualizarTabla();
  
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        // TODO add your handling code here:
        
        int row = tblUsuarios.getSelectedRow();
        System.out.println("--"+row);
        JTable target = (JTable)evt.getSource();
        txtCodigo.setText(target.getValueAt(target.getSelectedRow(), 0).toString());
        txtNombres.setText(target.getValueAt(target.getSelectedRow(), 1).toString());
        txtApellidos.setText(target.getValueAt(target.getSelectedRow(), 2).toString());
        txtFecha.setText(target.getValueAt(target.getSelectedRow(), 3).toString());
        txtEdad.setText(target.getValueAt(target.getSelectedRow(), 4).toString());
        txtDireccion.setText(target.getValueAt(target.getSelectedRow(), 5).toString());
        txtTelefono.setText(target.getValueAt(target.getSelectedRow(), 6).toString());
        txtCorreo.setText(target.getValueAt(target.getSelectedRow(), 7).toString());
        cmbEstado.setSelectedItem(target.getValueAt(target.getSelectedRow(),8).toString());
        cmbCiudad.setSelectedItem(target.getValueAt(target.getSelectedRow(), 9).toString());
        cmbNacionalidad.setSelectedItem(target.getValueAt(target.getSelectedRow(), 10).toString());
        txtPuesto.setText(target.getValueAt(target.getSelectedRow(), 11).toString());
        Ruta = tblUsuarios.getValueAt(tblUsuarios.getSelectedRow(), 12).toString();
        
        if (tblUsuarios.getValueAt(tblUsuarios.getSelectedRow(),12).toString().equals(""))
            {
                lblImagen.setIcon(null);
            }
            else
            {
                Imagen= new ImageIcon(((new ImageIcon((tblUsuarios.getValueAt(tblUsuarios.getSelectedRow(), 12).toString()))).getImage()).getScaledInstance(lblImagen.getWidth(),lblImagen.getHeight(), java.awt.Image.SCALE_SMOOTH));
                lblImagen.setIcon(Imagen);
            }      
        
         btnEliminar.setEnabled(true);
         btnModificar.setEnabled(true);
         btnAgregar.setEnabled(false);
         btnBuscar.setEnabled(true);
  
        
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
       UsuariosDAO objUsuariosDAO = new UsuariosDAO();
       objUsuariosDAO.Buscar(txtBuscar.getText(), cmbBuscar.getSelectedItem().toString(), tblUsuarios); 
//    ActualizarTabla();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(objUsuariosDAO.Eliminar(RecoletarDatos())==1)
        {
            JOptionPane.showMessageDialog(null,"Información eliminada");
        }
        ActualizarTabla();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Limpiar();
        
        cmbCiudad.addItem(" ");
        cmbEstado.setSelectedItem("Seleccione...");
        cmbNacionalidad.setSelectedItem("Seleccione...");
        lblImagen.setIcon(null);
        lblImagen.setText("Imagen");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if(objUsuariosDAO.Modificar(RecoletarDatos())==1)
        {
            JOptionPane.showMessageDialog(null,"Información modificada");
        }
        ActualizarTabla();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        // TODO add your handling code here:
        UsuariosDAO objUsuariosDAO = new UsuariosDAO();
        objUsuariosDAO.Buscar(txtBuscar.getText(), cmbBuscar.getSelectedItem().toString(), tblUsuarios);

        //        UsuarioDAO objUsuariosDAO = new UsuarioDAO();
        //        String Nombre = txtNombres.getText();
        //        DefaultTableModel modelo = new DefaultTableModel();
        //        modelo.addColumn("Código");
        //        modelo.addColumn("Nombres");
        //        modelo.addColumn("Apellidos");
        //        modelo.addColumn("Correo");
        //        modelo.addColumn("Estado");
        //        modelo.addColumn("Ciudad");
        //        modelo.addColumn("Imagen");
        //        ArrayList<Object[]> datos = new ArrayList<Object[]>();
        //        datos = objUsuariosDAO.buscar_tabla(Nombre);
        //        for(int i=0;i<datos.size();i++){
            //            modelo.addRow(datos.get(i));
            //        }
        //        tblUsuarios.setModel(modelo);

    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void btnExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExaminarActionPerformed
        // TODO add your handling code here:
         SeleccionarImagen = new JFileChooser();
        
        if (SeleccionarImagen.showOpenDialog(null) == JFileChooser.APPROVE_OPTION)
        {
            Ruta = "";
            Archivo = SeleccionarImagen.getSelectedFile();
            Ruta = Archivo.getAbsolutePath();
            Imagen = new ImageIcon(((new ImageIcon(Ruta)).getImage()).getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), java.awt.Image.SCALE_SMOOTH));
            lblImagen.setIcon(Imagen);
            lblImagen.setText("");
        }
        else
        {
            Ruta = "";
            lblImagen.setIcon(null);
        }
    }//GEN-LAST:event_btnExaminarActionPerformed

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
        LlenarCombobox();
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void txtFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltroActionPerformed

    private void txtFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyTyped
        // TODO add your handling code here:
        txtFiltro.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (txtFiltro.getText());
                txtFiltro.setText(cadena);
                repaint();
                Filtro();
            }
        });
        trsFiltro = new TableRowSorter(tblUsuarios.getModel());
        tblUsuarios.setRowSorter(trsFiltro);
    }//GEN-LAST:event_txtFiltroKeyTyped

    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped
        // TODO add your handling code here:
        //Validación De Letras
        
//        txtNombres.addKeyListener(new KeyAdapter() {
//           public void keyTyped(KeyEvent e) {
//               sololetrassinpunto(e);
//           }
//        });
        char c = evt.getKeyChar(); 
             
         
          if(Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume(); 
               
              JOptionPane.showMessageDialog(null,"Ingresa Solo Letras", "Error", JOptionPane.ERROR_MESSAGE);
              //txtNombres.setText("Ingresa Solo Letras"); 
               
          } 
    }//GEN-LAST:event_txtNombresKeyTyped

    private void txtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyTyped
        // TODO add your handling code here:
        //Validación De Letras
//        txtApellidos.addKeyListener(new KeyAdapter() {
//           public void keyTyped(KeyEvent e) {
//               sololetrassinpunto(e);
//           }
//        });
        
         char c = evt.getKeyChar(); 
             
         
          if(Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume(); 
               
              JOptionPane.showMessageDialog(null,"Ingresa Solo Letras", "Error", JOptionPane.ERROR_MESSAGE); 
          }
    }//GEN-LAST:event_txtApellidosKeyTyped

    private void txtFechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtFechaKeyTyped

    private void txtFechaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechaFocusLost
        // TODO add your handling code here:
        //Validación De Fecha
        
//        txtFecha.addKeyListener(new KeyAdapter() {
//           public void keyTyped(KeyEvent e) {
//               solofecha(e);
//           }
//        });
        if (isDate(txtFecha.getText()))
        {
            
        }
        
        else 
        { 
            JOptionPane.showMessageDialog(null, "Ingrese Una Fecha De Nacimiento Correcto", "Error", JOptionPane.ERROR_MESSAGE);
            txtFecha.requestFocus();
        }
           
    }//GEN-LAST:event_txtFechaFocusLost

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
        // TODO add your handling code here:
        //Validación De Números
        
        txtEdad.addKeyListener(new KeyAdapter() {
           public void keyTyped(KeyEvent e) {
               solonumerossinpunto(e);
           }
        });
        
            char c = evt.getKeyChar(); 
             
         
          if(Character.isLetter(c)) { 
              getToolkit().beep(); 
               
              evt.consume(); 
               
              JOptionPane.showMessageDialog(null,"Ingresa Solo Números", "Error", JOptionPane.ERROR_MESSAGE);
               
          } 
          else if (txtEdad.getText().length() >= 2) {
             evt.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
             JOptionPane.showMessageDialog(null, "Ha Excedido El Número Máximo De Caracteres!!! (2)", "Validando Datos",
                     JOptionPane.ERROR_MESSAGE);
         }
    }//GEN-LAST:event_txtEdadKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
        //Validación De Número
//        char c = evt.getKeyChar(); 
//             
//         
//          if(Character.isLetter(c)) { 
//              getToolkit().beep(); 
//               
//              evt.consume(); 
//               
//              JOptionPane.showMessageDialog(null,"Ingresa Un Teléfono Válido", "Error", JOptionPane.ERROR_MESSAGE); 
//          }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusLost
        // TODO add your handling code here:
        if (isEmail(txtCorreo.getText())) 
        {
            
        }
        else 
        {
            JOptionPane.showMessageDialog(null, "Ingrese Un Correo Correcto", "Error", JOptionPane.ERROR_MESSAGE);
            txtCorreo.requestFocus();
        }
    }//GEN-LAST:event_txtCorreoFocusLost

    private void txtPuestoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPuestoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar(); 
             
         
          if(Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume(); 
               
              JOptionPane.showMessageDialog(null,"Ingresa Solo Letras", "Error", JOptionPane.ERROR_MESSAGE); 
          }
    }//GEN-LAST:event_txtPuestoKeyTyped

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        new Usuarios().setVisible(true);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Ventas.main(null);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new Proveedores().setVisible(true);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        new Clientes().setVisible(true);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        new proyectoferreteria_7a.GUI.ConsultarFacturas().setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        new proyectoferreteria_7a.GUI.ConsultarVentas().setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed
  
public void Limpiar(){
  txtCodigo.setText("");
  txtNombres.setText("");
  txtEdad.setText("");
  txtDireccion.setText("");
  txtTelefono.setText("");
  txtCorreo.setText("");
  txtPuesto.setText("");
  txtFecha.setText("");
  txtApellidos.setText("");
  //lblImagen.setIcon(null);
  txtBuscar.setText("");
  Ruta = "";
  
  btnEliminar.setEnabled(false);
  btnModificar.setEnabled(false);
  btnAgregar.setEnabled(true);
  btnBuscar.setEnabled(true);
  
    
  } 
 public void ValidarCamposVacios() 
   {
       String nombres=txtNombres.getText();
       String apellidos=txtApellidos.getText();
       String fecha = txtFecha.getText();
       String edad=txtEdad.getText();
       String direccion=txtDireccion.getText();
       String telefono=txtTelefono.getText();
       String correo=txtCorreo.getText();
       String puesto=txtPuesto.getText();
       String estado = cmbEstado.getSelectedItem().toString();
       String ciudad = cmbCiudad.getSelectedItem().toString();
       String nacionalidad = cmbNacionalidad.getSelectedItem().toString();
       String imagen = lblImagen.getText();
       
       if(nombres.equalsIgnoreCase("")|| apellidos.equalsIgnoreCase("") || fecha.equalsIgnoreCase("") || edad.equalsIgnoreCase("") || direccion.equalsIgnoreCase("") || telefono.equalsIgnoreCase("") || correo.equalsIgnoreCase("") || estado.equalsIgnoreCase("") || ciudad.equalsIgnoreCase("") || nacionalidad.equalsIgnoreCase("") || puesto.equalsIgnoreCase("")){
       JOptionPane.showMessageDialog(null,"Faltan Ingresar Datos");
            
        }
   }
private void solonumerossinpunto(KeyEvent e) {
    char caracter = e.getKeyChar();
      // Verificar si la tecla pulsada no es un digito
      if(((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*corresponde a BACK_SPACE*/))
      {
         e.consume();  // ignorar el evento de teclado
      }
}
private void sololetrassinpunto(KeyEvent e) {
    char caracter = e.getKeyChar();
      // Verificar si la tecla pulsada no es un digito
      if(((caracter < 'a') || (caracter > 'z')) && (caracter != ' ' /*Si Se Permiten Espacios*/))
      {
         e.consume();  // ignorar el evento de teclado
      }
}
private void solofecha(KeyEvent e) {
    char caracter = e.getKeyChar();
      // Verificar si la tecla pulsada no es un digito
      if(((caracter < '0') || (caracter > '9')) && (caracter != '/' /*corresponde a BACK_SPACE*/))
      {
         e.consume();  // ignorar el evento de teclado
      }
}


//Validación De Correo
 public boolean isEmail(String correo) {
        Pattern pat = null;
        Matcher mat = null;        
        pat = Pattern.compile("^([0-9a-zA-Z]([_.w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-w]*[0-9a-zA-Z].)+([a-zA-Z]{2,9}.)+[a-zA-Z]{2,3})$");
        mat = pat.matcher(correo);
        if (mat.find()) {
            return true;
        }else{
            return false;
        }        
    }
//Validación De Fecha De Nacimiento
 public boolean isDate(String fechax) {
        try {
            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date fecha =  formatoFecha.parse(fechax);
            
            
        } catch (Exception e) {
            return false;
        }
        return true;
    }
 public void Filtro()
    {
        trsFiltro.setRowFilter(RowFilter.regexFilter(txtFiltro.getText(),0,1,2,3,4,5,6,7,8,9,10,11,12));
    }
public void LlenarCombobox()
        {
        
        if (cmbEstado.getSelectedItem().equals("Yucatán"))
        {
            cmbCiudad.removeAllItems();
            cmbCiudad.addItem("Mérida");
            cmbCiudad.addItem("Acancéh");
            cmbCiudad.addItem("Motul");
            cmbCiudad.addItem("Izamal");
            cmbCiudad.addItem("Halachó");
            cmbCiudad.addItem("Tizimín");
            cmbCiudad.addItem("Tixkokob");
            cmbCiudad.addItem("Valladolid");
            cmbCiudad.addItem("Progreso");
            cmbCiudad.addItem("Celestún");                       
        }
        
        if (cmbEstado.getSelectedItem().equals("Quintana Roo"))
        {
            cmbCiudad.removeAllItems();
            cmbCiudad.addItem("Cozumel");
            cmbCiudad.addItem("Isla Mujeres");
            cmbCiudad.addItem("Cancún");
            cmbCiudad.addItem("Solidaridad");
            cmbCiudad.addItem("Felipe Carillo Puerto");
            cmbCiudad.addItem("Playa del Carmen");
            cmbCiudad.addItem("Bacalar");
            cmbCiudad.addItem("José María Morelos");
            cmbCiudad.addItem("Puerto Morelos");
            cmbCiudad.addItem("Tulum");                       
        }
        
        
        if (cmbEstado.getSelectedItem().equals("México"))
        {
            cmbCiudad.removeAllItems();
            cmbCiudad.addItem("Veracruz");
            cmbCiudad.addItem("Tlalnepantla");
            cmbCiudad.addItem("Acapulco");
            cmbCiudad.addItem("Nezahualcoyotl");
            cmbCiudad.addItem("Tlaquepaque");
            cmbCiudad.addItem("Irapuato");
            cmbCiudad.addItem("Queretaro");
            cmbCiudad.addItem("Morelia");
            cmbCiudad.addItem("Ciudad Juarez");
            cmbCiudad.addItem("Mérida");
        }
        
        if (cmbEstado.getSelectedItem().equals("Seleccione..."))
        {
            cmbCiudad.removeAllItems();
            cmbCiudad.addItem("");
        }
        
    }
    public UsuariosBO RecoletarDatos(){
        
        ObjUsuariosBO.setCodigo(txtCodigo.getText());
        ObjUsuariosBO.setNombres(txtNombres.getText());
        ObjUsuariosBO.setApellidos(txtApellidos.getText());
        ObjUsuariosBO.setFechaNacimiento(txtFecha.getText());
        ObjUsuariosBO.setEdad(txtEdad.getText());
        ObjUsuariosBO.setDireccion(txtDireccion.getText());
        ObjUsuariosBO.setTelefono(txtTelefono.getText());
        ObjUsuariosBO.setCorreo(txtCorreo.getText());
        ObjUsuariosBO.setEstado(cmbEstado.getSelectedItem().toString());
        ObjUsuariosBO.setCiudad(cmbCiudad.getSelectedItem().toString());
        ObjUsuariosBO.setNacionalidad(cmbNacionalidad.getSelectedItem().toString());
        ObjUsuariosBO.setPuesto(txtPuesto.getText());
        ObjUsuariosBO.setImagen(Ruta);
//        
            //objUsuariosBO.setImagen(lblImagen.getText());
//        ObjUsuariosBO.setImagen(txt_ruta.getText());
        return ObjUsuariosBO;
    }
    
    public void ActualizarTabla(){
    tblUsuarios.setModel(objUsuariosDAO.Buscar(RecoletarDatos()));
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnExaminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbBuscar;
    private javax.swing.JComboBox<String> cmbCiudad;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbNacionalidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscarPor;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblCiudad1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFiltro;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtPuesto;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txt_ruta;
    // End of variables declaration//GEN-END:variables
}
